In [1]:
import numpy as np

In [8]:
parameters_2F_3nm = np.load(
    r"C:\Users\vie43sq\data_vincent\python_output\Chapter_I\0_5_modeling\2F\3nm\parameters_2F_3nm.npy"
)
parameters_2F_3nm

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 1.00000000e+00,
        1.00000000e+00, 1.00000000e+00],
       [2.30163836e-02, 4.14252897e-01, 5.62730719e-01, 2.51733761e+00,
        8.14254523e-01, 5.17348491e-02, 9.83263084e-03, 9.90167369e-01,
        2.13574038e+00, 3.46766023e-04]])

In [9]:
parameters_3F_3nm = np.load(
    r"C:\Users\vie43sq\data_vincent\python_output\Chapter_I\0_5_modeling\3F\3nm\parameters_3F_3nm.npy"
)
parameters_3F_3nm

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
        1.00000000e+00, 1.00000000e+00, 2.00000000e+00, 2.00000000e+00,
        2.00000000e+00, 2.00000000e+00],
       [4.36921210e-01, 5.63078790e-01, 9.69934950e-01, 4.09983333e-01,
        2.37322729e-01, 4.79813880e-01, 2.82863391e-01, 9.59407924e-01,
        4.68674762e-02, 1.00212859e-02, 7.93262119e-03, 9.92067379e-01,
        6.36874352e-01, 3.04638223e-04]])

In [10]:
parameters_4F_3nm = np.load(
    r"C:\Users\vie43sq\data_vincent\python_output\Chapter_I\0_5_modeling\4F\3nm\parameters_4F_3nm.npy"
)
parameters_4F_3nm

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
        2.00000000e+00, 2.00000000e+00, 2.00000000e+00, 2.00000000e+00,
        2.00000000e+00, 2.00000000e+00, 3.00000000e+00, 3.00000000e+00,
        3.00000000e+00, 3.00000000e+00],
       [3.70450174e-01, 6.29549826e-01, 9.50181112e-01, 7.30010531e-01,
        3.65924981e-01, 6.34075019e-01, 9.48421966e-01, 5.19412339e-01,
        2.96271535e-01, 3.33008480e-01, 3.70719985e-01, 9.46759691e-01,
        5.73643130e-02, 1.28064313e-02, 6.67525063e-03, 9.93324749e-01,
        9.38006879e-01, 3.82844597e-04]])

In [21]:
[print(f"{param:.2e}") for param in parameters_3F_3nm[1][:-10]]
print("---")
[print(f"{param:.2e}") for param in parameters_4F_3nm[1][-14:-10]];

4.37e-01
5.63e-01
9.70e-01
4.10e-01
---
3.66e-01
6.34e-01
9.48e-01
5.19e-01


In [20]:
[print(f"{param:.2e}") for param in parameters_2F_3nm[1][:-4]]
print("---")
[print(f"{param:.2e}") for param in parameters_3F_3nm[1][-10:-4]]
print("---")
[print(f"{param:.2e}") for param in parameters_4F_3nm[1][-10:-4]];

2.30e-02
4.14e-01
5.63e-01
2.52e+00
8.14e-01
5.17e-02
---
2.37e-01
4.80e-01
2.83e-01
9.59e-01
4.69e-02
1.00e-02
---
2.96e-01
3.33e-01
3.71e-01
9.47e-01
5.74e-02
1.28e-02


In [19]:
[print(f"{param:.2e}") for param in parameters_2F_3nm[1][-4:]]
print("---")
[print(f"{param:.2e}") for param in parameters_3F_3nm[1][-4:]]
print("---")
[print(f"{param:.2e}") for param in parameters_4F_3nm[1][-4:]];

9.83e-03
9.90e-01
2.14e+00
3.47e-04
---
7.93e-03
9.92e-01
6.37e-01
3.05e-04
---
6.68e-03
9.93e-01
9.38e-01
3.83e-04
