# Convolve and correlate (focus on numpy) explanation

## Convolve

In [2]:
import numpy as np

In [4]:
a = [1, 2, 3]
b = [0, 1, 0.5]
c = np.convolve(a, b)
c

array([0. , 1. , 2.5, 4. , 1.5])

Note that the result makes negative n (or t) possible, meaning that c[0] is c[n=-2]. See the formula on numpy.convolve documentation. See https://www.youtube.com/watch?v=QmcoPYUfbJ8 for intuition.

## Correlate

In [8]:
d = np.correlate(a, b, mode="full")
d

array([0.5, 2. , 3.5, 3. , 0. ])

https://stackoverflow.com/questions/643699/how-can-i-use-numpy-correlate-to-do-autocorrelation here it states that correlate is the convolution of a with inverse of b, lets test it

In [11]:
d_2 = np.convolve(a, b[::-1])
d_2

array([0.5, 2. , 3.5, 3. , 0. ])