# Tutorial: attributes of fluorophore classes

In [63]:
#user = r"\SagixOffice"  # HomeOffice
user = r"\vie43sq"  # University
import sys
sys.path.append(rf"C:\Users{user}\OneDrive - Universität Würzburg\GitHub\Photoswitching")

import numpy as np
import matplotlib.pyplot as plt
import src.fluorophore_systems as fs
import src.custom_plot as cp
import src.figures as fi
from IPython.display import HTML

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [64]:
rate_dict = dict(k_S0_S1=[7e6, "excitation"],  
                 k_S1_S0=[1e9, "fluorescent emission"], 
                 k_S1_T1=[1e6, "intersystem crossing"],   
                 k_T1_S0=[5e5, "vibrational relaxation"])

## Initialization

In [65]:
system = fs.GeneralModel(number=2, distances=1, rates=rate_dict)

In [66]:
system.number

2

In [67]:
system.distances

1

In [68]:
system.rates

{'k_S0_S1': [7000000.0, 'excitation'],
 'k_S1_S0': [1000000000.0, 'fluorescent emission'],
 'k_S1_T1': [1000000.0, 'intersystem crossing'],
 'k_T1_S0': [500000.0, 'vibrational relaxation']}

In [69]:
system.single_states

('S0', 'S1', 'T1', 'B')

In [70]:
system.Joined_States

<enum 'Joined_States'>

In [71]:
for joined_state in system.Joined_States:
    print(joined_state)
    print(joined_state.name)
    print(joined_state.value)

Joined_States.S0_S0
S0_S0
0
Joined_States.S0_S1
S0_S1
1
Joined_States.S0_T1
S0_T1
2
Joined_States.S0_B
S0_B
3
Joined_States.S1_S0
S1_S0
4
Joined_States.S1_S1
S1_S1
5
Joined_States.S1_T1
S1_T1
6
Joined_States.S1_B
S1_B
7
Joined_States.T1_S0
T1_S0
8
Joined_States.T1_S1
T1_S1
9
Joined_States.T1_T1
T1_T1
10
Joined_States.T1_B
T1_B
11
Joined_States.B_S0
B_S0
12
Joined_States.B_S1
B_S1
13
Joined_States.B_T1
B_T1
14
Joined_States.B_B
B_B
15


In [72]:
system.single_state_counter

{'S0_S0': array([2., 0., 0., 0.]),
 'S0_S1': array([1., 1., 0., 0.]),
 'S0_T1': array([1., 0., 1., 0.]),
 'S0_B': array([1., 0., 0., 1.]),
 'S1_S0': array([1., 1., 0., 0.]),
 'S1_S1': array([0., 2., 0., 0.]),
 'S1_T1': array([0., 1., 1., 0.]),
 'S1_B': array([0., 1., 0., 1.]),
 'T1_S0': array([1., 0., 1., 0.]),
 'T1_S1': array([0., 1., 1., 0.]),
 'T1_T1': array([0., 0., 2., 0.]),
 'T1_B': array([0., 0., 1., 1.]),
 'B_S0': array([1., 0., 0., 1.]),
 'B_S1': array([0., 1., 0., 1.]),
 'B_T1': array([0., 0., 1., 1.]),
 'B_B': array([0., 0., 0., 2.])}

In [73]:
system.single_state_id

{'S0_S0': array([0, 0]),
 'S0_S1': array([0, 1]),
 'S0_T1': array([0, 2]),
 'S0_B': array([0, 3]),
 'S1_S0': array([1, 0]),
 'S1_S1': array([1, 1]),
 'S1_T1': array([1, 2]),
 'S1_B': array([1, 3]),
 'T1_S0': array([2, 0]),
 'T1_S1': array([2, 1]),
 'T1_T1': array([2, 2]),
 'T1_B': array([2, 3]),
 'B_S0': array([3, 0]),
 'B_S1': array([3, 1]),
 'B_T1': array([3, 2]),
 'B_B': array([3, 3])}

In [74]:
system.state_names

['S0_S0',
 'S0_S1',
 'S0_T1',
 'S0_B',
 'S1_S0',
 'S1_S1',
 'S1_T1',
 'S1_B',
 'T1_S0',
 'T1_S1',
 'T1_T1',
 'T1_B',
 'B_S0',
 'B_S1',
 'B_T1',
 'B_B']

In [75]:
system.state_ids

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [76]:
system.state_identifier

{'S0_S0': 0,
 'S0_S1': 1,
 'S0_T1': 2,
 'S0_B': 3,
 'S1_S0': 4,
 'S1_S1': 5,
 'S1_T1': 6,
 'S1_B': 7,
 'T1_S0': 8,
 'T1_S1': 9,
 'T1_T1': 10,
 'T1_B': 11,
 'B_S0': 12,
 'B_S1': 13,
 'B_T1': 14,
 'B_B': 15}

In [77]:
system.transitions

{'S0_S0__S0_S0': (0, 0),
 'S0_S0__S0_S1': (0, 1),
 'S0_S0__S0_T1': (0, 2),
 'S0_S0__S0_B': (0, 3),
 'S0_S0__S1_S0': (0, 4),
 'S0_S0__S1_S1': (0, 5),
 'S0_S0__S1_T1': (0, 6),
 'S0_S0__S1_B': (0, 7),
 'S0_S0__T1_S0': (0, 8),
 'S0_S0__T1_S1': (0, 9),
 'S0_S0__T1_T1': (0, 10),
 'S0_S0__T1_B': (0, 11),
 'S0_S0__B_S0': (0, 12),
 'S0_S0__B_S1': (0, 13),
 'S0_S0__B_T1': (0, 14),
 'S0_S0__B_B': (0, 15),
 'S0_S1__S0_S0': (1, 0),
 'S0_S1__S0_S1': (1, 1),
 'S0_S1__S0_T1': (1, 2),
 'S0_S1__S0_B': (1, 3),
 'S0_S1__S1_S0': (1, 4),
 'S0_S1__S1_S1': (1, 5),
 'S0_S1__S1_T1': (1, 6),
 'S0_S1__S1_B': (1, 7),
 'S0_S1__T1_S0': (1, 8),
 'S0_S1__T1_S1': (1, 9),
 'S0_S1__T1_T1': (1, 10),
 'S0_S1__T1_B': (1, 11),
 'S0_S1__B_S0': (1, 12),
 'S0_S1__B_S1': (1, 13),
 'S0_S1__B_T1': (1, 14),
 'S0_S1__B_B': (1, 15),
 'S0_T1__S0_S0': (2, 0),
 'S0_T1__S0_S1': (2, 1),
 'S0_T1__S0_T1': (2, 2),
 'S0_T1__S0_B': (2, 3),
 'S0_T1__S1_S0': (2, 4),
 'S0_T1__S1_S1': (2, 5),
 'S0_T1__S1_T1': (2, 6),
 'S0_T1__S1_B': (2, 7),
 'S0_T

In [78]:
system.assigned_rate_dict

{'S0_S0__S0_S1': 7000000.0,
 'S0_S0__S1_S0': 7000000.0,
 'S0_S1__S1_S1': 7000000.0,
 'S0_T1__S1_T1': 7000000.0,
 'S0_B__S1_B': 7000000.0,
 'S1_S0__S1_S1': 7000000.0,
 'T1_S0__T1_S1': 7000000.0,
 'B_S0__B_S1': 7000000.0,
 'S0_S1__S0_S0': 1000000000.0,
 'S1_S0__S0_S0': 1000000000.0,
 'S1_S1__S0_S1': 1000000000.0,
 'S1_S1__S1_S0': 1000000000.0,
 'S1_T1__S0_T1': 1000000000.0,
 'S1_B__S0_B': 1000000000.0,
 'T1_S1__T1_S0': 1000000000.0,
 'B_S1__B_S0': 1000000000.0,
 'S0_S1__S0_T1': 1000000.0,
 'S1_S0__T1_S0': 1000000.0,
 'S1_S1__S1_T1': 1000000.0,
 'S1_S1__T1_S1': 1000000.0,
 'S1_T1__T1_T1': 1000000.0,
 'S1_B__T1_B': 1000000.0,
 'T1_S1__T1_T1': 1000000.0,
 'B_S1__B_T1': 1000000.0,
 'S0_T1__S0_S0': 500000.0,
 'S1_T1__S1_S0': 500000.0,
 'T1_S0__S0_S0': 500000.0,
 'T1_S1__S0_S1': 500000.0,
 'T1_T1__S0_T1': 500000.0,
 'T1_T1__T1_S0': 500000.0,
 'T1_B__S0_B': 500000.0,
 'B_T1__B_S0': 500000.0}

In [79]:
system.rate_id_dict

{(0, 1): 0,
 (0, 4): 0,
 (1, 5): 0,
 (2, 6): 0,
 (3, 7): 0,
 (4, 5): 0,
 (8, 9): 0,
 (12, 13): 0,
 (1, 0): 1,
 (4, 0): 1,
 (5, 1): 1,
 (5, 4): 1,
 (6, 2): 1,
 (7, 3): 1,
 (9, 8): 1,
 (13, 12): 1,
 (1, 2): 2,
 (4, 8): 2,
 (5, 6): 2,
 (5, 9): 2,
 (6, 10): 2,
 (7, 11): 2,
 (9, 10): 2,
 (13, 14): 2,
 (2, 0): 3,
 (6, 4): 3,
 (8, 0): 3,
 (9, 1): 3,
 (10, 2): 3,
 (10, 8): 3,
 (11, 3): 3,
 (14, 12): 3}

In [80]:
system.rate_name_dict

{(0, 1): 'excitation',
 (0, 4): 'excitation',
 (1, 5): 'excitation',
 (2, 6): 'excitation',
 (3, 7): 'excitation',
 (4, 5): 'excitation',
 (8, 9): 'excitation',
 (12, 13): 'excitation',
 (1, 0): 'fluorescent emission',
 (4, 0): 'fluorescent emission',
 (5, 1): 'fluorescent emission',
 (5, 4): 'fluorescent emission',
 (6, 2): 'fluorescent emission',
 (7, 3): 'fluorescent emission',
 (9, 8): 'fluorescent emission',
 (13, 12): 'fluorescent emission',
 (1, 2): 'intersystem crossing',
 (4, 8): 'intersystem crossing',
 (5, 6): 'intersystem crossing',
 (5, 9): 'intersystem crossing',
 (6, 10): 'intersystem crossing',
 (7, 11): 'intersystem crossing',
 (9, 10): 'intersystem crossing',
 (13, 14): 'intersystem crossing',
 (2, 0): 'vibrational relaxation',
 (6, 4): 'vibrational relaxation',
 (8, 0): 'vibrational relaxation',
 (9, 1): 'vibrational relaxation',
 (10, 2): 'vibrational relaxation',
 (10, 8): 'vibrational relaxation',
 (11, 3): 'vibrational relaxation',
 (14, 12): 'vibrational relaxat

In [81]:
system.transition_dict

{0: 'excitation',
 1: 'fluorescent emission',
 2: 'intersystem crossing',
 3: 'vibrational relaxation'}

There are 16 states, hence the transition_matrix will have 16 rows and 16 columns. See tutorial on Gillespie Algorithm for more insight.

In [82]:
system.initial_row_vector

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [83]:
system.transition_matrix[:2]

array([[0.00000000e+00, 5.00000000e-01, 0.00000000e+00, 0.00000000e+00,
        5.00000000e-01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [9.92063492e-01, 0.00000000e+00, 9.92063492e-04, 0.00000000e+00,
        0.00000000e+00, 6.94444444e-03, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [84]:
system.row_sums

array([1.4000e+07, 1.0080e+09, 7.5000e+06, 7.0000e+06, 1.0080e+09,
       2.0020e+09, 1.0015e+09, 1.0010e+09, 7.5000e+06, 1.0015e+09,
       1.0000e+06, 5.0000e+05, 7.0000e+06, 1.0010e+09, 5.0000e+05,
       0.0000e+00])

In [85]:
system.absorbing_states

[15]

## Simulation

In [86]:
system.simulate(n_steps=10)

In [87]:
system.time_series

array([0.00000000e+00, 1.28818253e-08, 1.41137716e-08, 1.60208337e-08,
       1.62543548e-08, 4.29502104e-08, 4.29687567e-08, 7.60537441e-08,
       7.65606607e-08, 7.68629348e-08, 7.71209086e-08])

In [88]:
system.time_step_series

array([0.00000000e+00, 1.28818253e-08, 1.23194634e-09, 1.90706206e-09,
       2.33521101e-10, 2.66958556e-08, 1.85463106e-11, 3.30849875e-08,
       5.06916514e-10, 3.02274099e-10, 2.57973833e-10])

In [89]:
system.state_series

array([0, 4, 0, 4, 0, 1, 0, 4, 0, 4, 0], dtype=int64)

In [90]:
system.transition_series

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int64)

## Processing

In [91]:
system.process()

In [92]:
system.duplices

[[1, 4], [2, 8], [3, 12], [6, 9], [7, 13], [11, 14]]

In [93]:
system.unique_series

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0], dtype=int64)

In [94]:
system.unique_states

array([0, 1], dtype=int64)

In [95]:
system.unique_joined_states

[<Joined_States.S0_S0: 0>, <Joined_States.S0_S1: 1>]

In [96]:
system.unique_names

['S0_S0', 'S0_S1']

In [97]:
system.unique_transitions

{'S0_S0__S0_S0': (0, 0),
 'S0_S0__S0_S1': (0, 1),
 'S0_S1__S0_S0': (1, 0),
 'S0_S1__S0_S1': (1, 1)}

In [98]:
system.unique_series_converted

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0], dtype=int64)

In [99]:
system.single_state_series

array([[0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

In [100]:
system.single_state_lifetimes

{'single_state_occurrences': [array([0., 1., 0., 1., 0., 1., 0., 1., 0.]),
  array([0., 1., 0.])],
 'single_state_occurrences_all': array([0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 1., 0.]),
 'lifetimes_fluorophore': [array([1.28818253e-08, 1.23194634e-09, 1.90706206e-09, 2.33521101e-10,
         5.97993894e-08, 5.06916514e-10, 3.02274099e-10, 2.57973833e-10]),
  array([4.29502104e-08, 1.85463106e-11])],
 'lifetimes_single_states': [[array([1.28818253e-08, 1.90706206e-09, 5.97993894e-08, 3.02274099e-10]),
   array([1.23194634e-09, 2.33521101e-10, 5.06916514e-10, 2.57973833e-10]),
   array([], dtype=float64),
   array([], dtype=float64)],
  [array([4.29502104e-08]),
   array([1.85463106e-11]),
   array([], dtype=float64),
   array([], dtype=float64)]],
 'lifetimes_single_states_all': [array([1.28818253e-08, 1.90706206e-09, 5.97993894e-08, 3.02274099e-10,
         4.29502104e-08]),
  array([1.23194634e-09, 2.33521101e-10, 5.06916514e-10, 2.57973833e-10,
         1.85463106e-11]),
  array([

In [101]:
system.transition_lifetimes

{'transition_occurrences': [array([0, 1, 0, 1, 0, 1, 0, 1], dtype=int64),
  array([0, 1], dtype=int64)],
 'transition_occurrences_all': array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int64),
 'transition_times': [[array([1.28818253e-08, 1.90706206e-09, 5.97993894e-08, 3.02274099e-10]),
   array([1.23194634e-09, 2.33521101e-10, 5.06916514e-10, 2.57973833e-10]),
   array([], dtype=float64),
   array([], dtype=float64)],
  [array([4.29502104e-08]),
   array([1.85463106e-11]),
   array([], dtype=float64),
   array([], dtype=float64)]],
 'transition_times_all': [array([1.28818253e-08, 1.90706206e-09, 5.97993894e-08, 3.02274099e-10,
         4.29502104e-08]),
  array([1.23194634e-09, 2.33521101e-10, 5.06916514e-10, 2.57973833e-10,
         1.85463106e-11]),
  array([], dtype=float64),
  array([], dtype=float64)],
 'mean_transition_times': array([[1.87226377e-08, 5.57589448e-10,            nan,            nan],
        [4.29502104e-08, 1.85463106e-11,            nan,            nan]]),
 'mean_tr

## Emitters

In [102]:
system.emitters()

In [103]:
system.emitting_transitions

['S0_S1__S0_S0']

In [104]:
system.emitting_transitions_indices

[(1, 0)]

In [105]:
system.emitting_mask

array([False, False,  True, False,  True, False,  True, False,  True,
       False,  True])

In [108]:
system.detected_emission_mask

array([False, False,  True, False,  True, False,  True, False,  True,
       False,  True])

In [54]:
system.events_at

array([1.41137716e-08, 1.62543548e-08, 4.29687567e-08, 7.65606607e-08,
       7.71209086e-08])

In [ ]:
system.last_parameters

In [56]:
system.pandas_series

0.0    5.0
dtype: float64

In [57]:
system.on_periods

array([1])

In [58]:
system.off_periods

array([], dtype=int32)

In [59]:
system.statistics

{'total_events': 5,
 'mean_time_between_events': 1.5751784244471554e-08,
 'total_detected_events': 5}

## FCS

In [125]:
system.simulate(n_steps=10000)

In [126]:
system.process()

In [127]:
system.emitters(unit="s", resample="0.05ms", photon_collection=1, use_unique=True)

In [135]:
system.fcs()

In [136]:
system.autocorrelation

(array([0.   , 0.005, 0.01 ]), array([ 0.06841329, -0.0042759 , -0.00308011]))