In [78]:
#user = r"\SagixOffice"  # HomeOffice
user = r"\vie43sq"  # University
import sys
sys.path.append(rf"C:\Users{user}\OneDrive - Universität Würzburg\GitHub\Photoswitching")

import numpy as np
import matplotlib.pyplot as plt
import src.fluorophore_systems as fs
import src.custom_plot as cp
import src.figures as fi
from IPython.display import HTML

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [79]:
rates = [['k_S0_S1', 7e6, "excitation", False],  
         ['k_S1_S0', 1e9, "fluorescent emission", True], 
         ['k_S1_T1', 1e6, "intersystem crossing", False],   
         ['k_T1_S0', 5e5, "vibrational relaxation", False],
         ['k_S1_S0', 1e9, "vibrational relaxation", False]]

In [80]:
system = fs.GeneralModel(number_fluorophores=2, distances=1, rates=rates)

In [54]:
system.single_states

{0: 'S0', 1: 'S1', 2: 'T1', 3: 'B'}

In [37]:
system.single_transitions

,name,rate,trivial_name,fluorescence
id,,,,
0,k_S0_S1,7.000000e+06,excitation,False
1,k_S1_S0,1.000000e+09,fluorescent emission,True
2,k_S1_T1,1.000000e+06,intersystem crossing,False
3,k_T1_S0,5.000000e+05,vibrational relaxation,False
4,k_S1_S0,1.000000e+09,vibrational relaxation,False


In [38]:
system.joined_states

,name,single_states,single_state_counter,absorbing
id,,,,
0,S0_S0,"[0, 0]","[2, 0, 0, 0]",False
1,S0_S1,"[0, 1]","[1, 1, 0, 0]",False
2,S0_T1,"[0, 2]","[1, 0, 1, 0]",False
3,S0_B,"[0, 3]","[1, 0, 0, 1]",False
4,S1_S0,"[1, 0]","[1, 1, 0, 0]",False
5,S1_S1,"[1, 1]","[0, 2, 0, 0]",False
6,S1_T1,"[1, 2]","[0, 1, 1, 0]",False
7,S1_B,"[1, 3]","[0, 1, 0, 1]",False
8,T1_S0,"[2, 0]","[1, 0, 1, 0]",False


In [39]:
system.joined_transitions

,name,joined_states_id,single_transition_id,rate,trivial_name,fluorescence
id,,,,,,
0,S0_S0__S0_S1,"(0, 1)",0,7.000000e+06,excitation,False
1,S0_S0__S1_S0,"(0, 4)",0,7.000000e+06,excitation,False
2,S0_S1__S1_S1,"(1, 5)",0,7.000000e+06,excitation,False
3,S0_T1__S1_T1,"(2, 6)",0,7.000000e+06,excitation,False
4,S0_B__S1_B,"(3, 7)",0,7.000000e+06,excitation,False
5,S1_S0__S1_S1,"(4, 5)",0,7.000000e+06,excitation,False
6,T1_S0__T1_S1,"(8, 9)",0,7.000000e+06,excitation,False
7,B_S0__B_S1,"(12, 13)",0,7.000000e+06,excitation,False
8,S0_S1__S0_S0,"(1, 0)",1,1.000000e+09,fluorescent emission,True


In [42]:
system.row_sums

array([1.4000e+07, 2.0080e+09, 7.5000e+06, 7.0000e+06, 2.0080e+09,
       4.0020e+09, 2.0015e+09, 2.0010e+09, 7.5000e+06, 2.0015e+09,
       1.0000e+06, 5.0000e+05, 7.0000e+06, 2.0010e+09, 5.0000e+05,
       0.0000e+00])

In [81]:
system.simulate(n_steps=20, seed=10)

In [45]:
system.state_series

array([0, 1, 0, 1, 0, 4, 0, 4, 0, 4, 0, 4, 0, 1, 0, 4, 0, 4, 0, 1, 0],
      dtype=int64)

In [82]:
system.time_series

array([0.00000000e+00, 3.21396983e-09, 3.30769740e-09, 5.10120096e-08,
       5.11974982e-08, 1.12231011e-07, 1.12326613e-07, 1.51759715e-07,
       1.51854249e-07, 2.89786972e-07, 2.90768425e-07, 3.96962286e-07,
       3.97551495e-07, 4.44558648e-07, 4.45188286e-07, 5.23568268e-07,
       5.24498570e-07, 5.34454544e-07, 5.35121613e-07, 6.77215513e-07,
       6.77693689e-07])

In [85]:
system.transition_series

array([0, 1, 0, 1, 0, 4, 0, 1, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4],
      dtype=int64)

In [108]:
index = system.single_transitions.loc[system.single_transitions['fluorescence'] == True].index.to_numpy()

In [109]:
index

array([1], dtype=int64)

In [112]:
indices = np.where(system.transition_series == index)[0]+1

In [113]:
system.time_series[indices]

array([3.30769740e-09, 5.11974982e-08, 1.51854249e-07])

In [47]:
system.time_step_series

array([0.00000000e+00, 3.21396983e-09, 9.37275736e-11, 4.77043122e-08,
       1.85488577e-10, 6.10335133e-08, 9.56018183e-11, 3.94331014e-08,
       9.45343189e-11, 1.37932723e-07, 9.81452451e-10, 1.06193862e-07,
       5.89209133e-10, 4.70071528e-08, 6.29637497e-10, 7.83799824e-08,
       9.30301933e-10, 9.95597364e-09, 6.67069447e-10, 1.42093900e-07,
       4.78176387e-10])

In [84]:
system.process()

In [71]:
system.transition_series

array([0, 1, 0, 1, 0, 4, 0, 4, 0, 4, 0, 4, 0, 1, 0, 4, 0, 4, 0, 1],
      dtype=int64)

In [72]:
system.single_state_series

array([[0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 0., 1.,
        0., 1., 0., 0., 0.],
       [0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 1., 0.]])

In [75]:
system.single_state_lifetimes

{'single_state_occurrences': [array([0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.]),
  array([0., 1., 0., 1., 0., 1., 0., 1., 0.])],
 'single_state_occurrences_all': array([0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 1., 0., 1.,
        0., 1., 0., 1., 0.]),
 'lifetimes_fluorophore': [array([1.12231011e-07, 9.56018183e-11, 3.94331014e-08, 9.45343189e-11,
         1.37932723e-07, 9.81452451e-10, 1.06193862e-07, 5.89209133e-10,
         1.26016773e-07, 9.30301933e-10, 9.95597364e-09, 6.67069447e-10]),
  array([3.21396983e-09, 9.37275736e-11, 4.77043122e-08, 1.85488577e-10,
         3.93361150e-07, 6.29637497e-10, 2.32027227e-07, 4.78176387e-10])],
 'lifetimes_single_states': [[array([1.12231011e-07, 3.94331014e-08, 1.37932723e-07, 1.06193862e-07,
          1.26016773e-07, 9.95597364e-09]),
   array([9.56018183e-11, 9.45343189e-11, 9.81452451e-10, 5.89209133e-10,
          9.30301933e-10, 6.67069447e-10]),
   array([], dtype=float64),
   array([], dtype=float64)],
  [arr

In [76]:
system.transition_lifetimes

{'transition_occurrences': [array([0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4], dtype=int64),
  array([0, 1, 0, 1, 0, 1, 0, 1], dtype=int64)],
 'transition_occurrences_all': array([0, 1, 0, 1, 0, 4, 0, 4, 0, 4, 0, 4, 0, 1, 0, 4, 0, 4, 0, 1],
       dtype=int64),
 'transition_times': [[array([1.12231011e-07, 3.94331014e-08, 1.37932723e-07, 1.06193862e-07,
          1.26016773e-07, 9.95597364e-09]),
   array([], dtype=float64),
   array([], dtype=float64),
   array([], dtype=float64),
   array([9.56018183e-11, 9.45343189e-11, 9.81452451e-10, 5.89209133e-10,
          9.30301933e-10, 6.67069447e-10])],
  [array([3.21396983e-09, 4.77043122e-08, 3.93361150e-07, 2.32027227e-07]),
   array([9.37275736e-11, 1.85488577e-10, 6.29637497e-10, 4.78176387e-10]),
   array([], dtype=float64),
   array([], dtype=float64),
   array([], dtype=float64)]],
 'transition_times_all': [array([1.12231011e-07, 3.94331014e-08, 1.37932723e-07, 1.06193862e-07,
         1.26016773e-07, 9.95597364e-09, 3.21396983e-09, 4.7704